app:
  build: .
  volumes:
    - ./:/app/
    - /app/node_modules
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - BUILDKITE_TAG
    - GITHUB_RELEASE_ACCESS_TOKEN
    - DOCKER_HUB_TRIGGER_TOKEN
