steps:
  - name: ":docker: Build"
    command: "docker-compose build"

  - wait

  - name: ":selenium: Test"
    command: "docker-compose run app npm test"

  - wait

  - name: "Publish to ECR"
    command: 
      - "docker build -t buildkiteexample ."
      - "docker tag buildkiteexample:latest 327089805594.dkr.ecr.us-east-2.amazonaws.com/buildkiteexample:latest"
      - "docker push 327089805594.dkr.ecr.us-east-2.amazonaws.com/buildkiteexample:latest"
    plugins:
      ecr#v1.1.4:
        login: true