steps:
  - name: ":docker: Build"
    command: "docker-compose build"

  - wait

  - name: ":selenium: Test"
    command: "docker-compose run app npm test"

  - wait

  - name: ":npm: Build and Publish"
    command: "docker-compose run app .buildkite/scripts/publish.sh"